### ISSUE TITLE
[5pt] create Argo workflow to generate SI observation

### ISSUE THREAD

**Issue by goern** [thoth-station/workflows#26]
As Thoth,
I want to run an Argo Workflow
so that a bandit-based SI report is generated,
and so that the report is stored to S3
and so that the report is synced to the graph

Story-Points: 5

**Acceptance Criteria**

* run workflow from commandline
* workflow will:
  * download index_package_version to a tmp dir
  * compute SI on index_package_version -> S3
  * aggregate it into one single score -> S3
  * sync to graph

**Comment by pacospace** [comment]
This was done by @KPostOffice, it can be closed! https://github.com/thoth-station/thoth-application/pull/53
