### ISSUE TITLE
create workflow to analyse missing packages

### ISSUE THREAD

**Issue by goern** [thoth-station/workflows#6]
Based on an advise log, we can create a list of python packages that are missing in our knowledge graph. This list of packages should be added by submitting them for solving and analysis.
The workflow could use the advise log as an input, and could be triggered by all advise runs.

**Comment by goern** [comment]
https://trello.com/c/JJLG5TYS

**Comment by goern** [comment]
/unassign @bissenbay 
/assign @KPostOffice 
/remove-lifecycle stale

@KPostOffice could you have a look if this is implemented by investigator and friends? thx!

**Comment by KPostOffice** [comment]
Currently nothing is being done with the messages. It looks like Sai was working on implementing it as part of the `kebechet_administrator` workflow in workflow-helpers but never got around to it.

**Comment by harshad16** [comment]
This is already available with the help of workflow-helper and message which extract packages that is not existing while an advise and trigger for solving them.
https://github.com/thoth-station/thoth-application/blob/master/adviser/base/argo-workflows/parse-adviser-output.yaml
https://github.com/thoth-station/workflow-helpers/blob/master/parse_adviser_output.py#L103

Already demoed on
https://www.youtube.com/watch?v=xIbYF4UJ5Gs&t=24s

closing this issue.
Thank you everyone.
